--- #YAML:1.0
name:               Net-Comcast-Customer
version:            1.0
abstract:           Comcast Customer Central web interface
author:
    - Ken Dreyer <ktdreyer@ktdreyer.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Date::Calc:      0
    Net::Netrc:      0
    Test::More:      0
    WWW::Mechanize:  0
resources:
    homepage:    http://www.ktdreyer.com
    license:     http://dev.perl.org/licenses/
    Repository:  https://gitorious.org/ktdreyer/net-comcast-customer
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
